/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApplyRouteImport } from "./routes/apply";
import { Route as ProofRouteImport } from "./routes/proof";
import { Route as ServicesRouteImport } from "./routes/services";
import { Route as StoryRouteImport } from "./routes/story";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApplyRoute = ApplyRouteImport.update({
  id: "/apply",
  path: "/apply",
  getParentRoute: () => rootRouteImport,
} as any);
const ProofRoute = ProofRouteImport.update({
  id: "/proof",
  path: "/proof",
  getParentRoute: () => rootRouteImport,
} as any);
const ServicesRoute = ServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRouteImport,
} as any);
const StoryRoute = StoryRouteImport.update({
  id: "/story",
  path: "/story",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/apply": typeof ApplyRoute;
  "/proof": typeof ProofRoute;
  "/services": typeof ServicesRoute;
  "/story": typeof StoryRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/apply": typeof ApplyRoute;
  "/proof": typeof ProofRoute;
  "/services": typeof ServicesRoute;
  "/story": typeof StoryRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/apply": typeof ApplyRoute;
  "/proof": typeof ProofRoute;
  "/services": typeof ServicesRoute;
  "/story": typeof StoryRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/apply" | "/proof" | "/services" | "/story";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/apply" | "/proof" | "/services" | "/story";
  id: "__root__" | "/" | "/apply" | "/proof" | "/services" | "/story";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApplyRoute: typeof ApplyRoute;
  ProofRoute: typeof ProofRoute;
  ServicesRoute: typeof ServicesRoute;
  StoryRoute: typeof StoryRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/apply": {
      id: "/apply";
      path: "/apply";
      fullPath: "/apply";
      preLoaderRoute: typeof ApplyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/proof": {
      id: "/proof";
      path: "/proof";
      fullPath: "/proof";
      preLoaderRoute: typeof ProofRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/services": {
      id: "/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof ServicesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/story": {
      id: "/story";
      path: "/story";
      fullPath: "/story";
      preLoaderRoute: typeof StoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  ProofRoute: ProofRoute,
  ServicesRoute: ServicesRoute,
  StoryRoute: StoryRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
